### ISSUE TITLE
The right-click menu of the jsdebugger doesn't work

### ISSUE THREAD

**Issue by WeijianXu** [rDr4g0n/JsDebuggr#30]
I can't use the jsdebugger when I installed it. The right-click menu can be displayed but doesn't work and the default key bindings also don't. I don't know what happened.
My environment : sublime 3(3126), window7(64bit), node 7.10.0.

**Comment by rDr4g0n** [comment]
Are there any errors in the sublime text console? You can find it at view > show console.

**Comment by agrippanux** [comment]
I get the same error,

Installed Packages/JsDebuggr.sublime-package", line 26, in get_current_syntax
TypeError: 'NoneType' object is not iterable

Sublime 3 build 3143

**Comment by njohnson7** [comment]
I get the same error too. All the menu options are grayed out and the hotkeys don't do anything.

Here's the error message:
```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 428, in <lambda>
    run_callback('on_load', callback, lambda: callback.on_load(v))
  File "jsdebuggr in /home/xxxx/.config/sublime-text-3/Installed Packages/JsDebuggr.sublime-package", line 210, in on_load
  File "utils in /home/xxxx/.config/sublime-text-3/Installed Packages/JsDebuggr.sublime-package", line 26, in get_current_syntax
TypeError: 'NoneType' object is not iterable
```
